import type { Metadata } from "next";
import { Silkscreen } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/providers/LayoutProvider";

const silkscreen = Silkscreen({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FundMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={silkscreen.className}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
